name = "天空戦国 (Tenkū Sengoku)"
author = "west3436"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c622ec6874bb3147363834d1ee0bde81bb2595facb1f74c248fa174e796cea6a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
