name = "天空戦国 (Tenkū Sengoku)"
author = "west3436"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44c99c8ed8031bf0144ae1c85199f05e5a6a999224c438367c426782fa05446c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
