name = "天空戦国 (Tenkū Sengoku)"
author = "west3436"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6fa9d7d9af4382f02298605735bae195edde2d5c639568d4e880bea1a29febb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
