// Lawless NW frontier: blocks chunk claims in Korea/China so the region can never
// be made PvP-safe. Japan safety itself comes from FTB Chunks config
// (pvp_mode=per_team, def_pvp=false) — see docs/server-config-pvp.md.
//
// This file is BOTH a KubeJS startup script AND a Node-testable module: the pure
// helpers are defined unconditionally; the KubeJS event wiring (Task 4) is guarded
// by `typeof StartupEvents`, and a Node-only `module.exports` lives at the bottom.

// Generated by build/derive_lawless_regions.py — tune in-game (see that script).
const LAWLESS_REGIONS = [
  { id: 'korea_china', minX: -10688, minZ: -12078, maxX: -4568, maxZ: 2059 },
]
const LAWLESS_DIMENSION = 'minecraft:overworld'

// A chunk's 16x16 block extent overlaps the box (inclusive block coords).
function chunkInBox(cx, cz, box) {
  const x0 = cx * 16, x1 = x0 + 15
  const z0 = cz * 16, z1 = z0 + 15
  return x1 >= box.minX && x0 <= box.maxX && z1 >= box.minZ && z0 <= box.maxZ
}

function isLawlessChunk(cx, cz) {
  for (let i = 0; i < LAWLESS_REGIONS.length; i++) {
    if (chunkInBox(cx, cz, LAWLESS_REGIONS[i])) return true
  }
  return false
}

// Pure claim decision (no Java calls) so it is unit-testable under Node.
// ctx: { dimension: string, isOp: boolean, cx: int, cz: int } -> 'pass' | 'reject'
function claimDecision(ctx) {
  if (ctx.dimension !== LAWLESS_DIMENSION) return 'pass'  // overworld-only
  if (ctx.isOp) return 'pass'                              // ops bypass
  if (isLawlessChunk(ctx.cx, ctx.cz)) return 'reject'
  return 'pass'
}

if (typeof StartupEvents !== 'undefined') {
  const ClaimedChunkEvent = Java.loadClass('dev.ftb.mods.ftbchunks.api.event.ClaimedChunkEvent')
  const CompoundEventResult = Java.loadClass('dev.architectury.event.CompoundEventResult')
  const ClaimResult = Java.loadClass('dev.ftb.mods.ftbchunks.api.ClaimResult')

  ClaimedChunkEvent.BEFORE_CLAIM.register((source, chunk) => {
    const pos = chunk.getPos()
    const decision = claimDecision({
      dimension: pos.dimension().location().toString(),
      isOp: source.hasPermission(2),
      cx: pos.x(),
      cz: pos.z(),
    })
    if (decision === 'reject') {
      return CompoundEventResult.interruptFalse(
        ClaimResult.customProblem('The Korea–China frontier is lawless — land cannot be claimed here.')
      )
    }
    return CompoundEventResult.pass()
  })
}

// Node-only export (Rhino has no `module`, so this is skipped in KubeJS).
// NOTE: the WHOLE file is parsed by KubeJS's Rhino before this runtime guard runs,
// and that Rhino rejects ES6 shorthand object properties ({ a, b }). Use explicit
// `key: value` pairs here so the file parses under both Rhino and Node.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    chunkInBox: chunkInBox,
    isLawlessChunk: isLawlessChunk,
    claimDecision: claimDecision,
    LAWLESS_REGIONS: LAWLESS_REGIONS,
    LAWLESS_DIMENSION: LAWLESS_DIMENSION,
  }
}
